# .goreleaser.yml

builds:
  -
    id: "research"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - SECAI_ID=aigent-research
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./examples/research/cmd
    binary: aigent-research
    ldflags:
      - -s -w # Remove debug info, strip symbols (common optimization)
      - -X main.id=aigent-research



  -
    id: "cook"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - SECAI_ID=aigent-cook
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./examples/cook/cmd
    binary: aigent-cook
    ldflags:
      - -s -w # Remove debug info, strip symbols (common optimization)
      - -X main.id=aigent-cook

archives:
  -
    id: "aigent-research"
    format: tar.gz
    name_template: "aigent-research_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    # dont add readmes etc
    files: [""]
    builds:
      - research

  -
    id: "aigent-cook"
    format: tar.gz
    name_template: "aigent-cook_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    # dont add readmes etc
    files: [""]
    builds:
      - cook

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: pancsta
    name: secai
  draft: true
  replace_existing_draft: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^refactor:'
      - '^style:'
      - '^ci:'
      - '^perf:'
      - '^revert:'
snapshot:
  name_template: "{{ .Tag }}-next"