version: '3'
dotenv: [ '.env' ]
includes:
  shared:
    taskfile: ./config
    flatten: true
    excludes: [install-deps]

tasks:

  docker:
    env:
      DOCKER_BUILDKIT: 1
    cmd: docker build -t secai/{{.SECAI_ID}}
      --build-arg SECAI_ID="{{.SECAI_ID}}"
      -f deploy/agent/Dockerfile ..

  docker-compose:
    dotenv: ["deploy/agent/agent.env"]
#    cmd: env
    cmd: docker-compose -f ./deploy/agent/docker-compose.yml
      up -d
#      up -d --force-recreate

  docker-compose-stop:
    cmd: docker-compose -f ./deploy/agent/docker-compose.yml
      down

  dev-docker:
    env:
      DOCKER_BUILDKIT: 1
    cmd: docker build -t secai/{{.SECAI_ID}}-dev
      --build-arg SECAI_ID="{{.SECAI_ID}}"
      -f deploy/agent/Dockerfile ..

  dev-docker-compose:
    dotenv: ["deploy/agent/agent.env"]
    env:
      SECAI_ENV: "-dev"
#    cmd: env
    cmd: docker-compose -f ./deploy/agent/docker-compose.yml
      up -d
#      up -d --force-recreate

  dev-docker-compose-stop:
    env:
      SECAI_ENV: "-dev"
    cmd: docker-compose -f ./deploy/agent/docker-compose.yml
      down

  ex-deepresearch-delve:
    cmds:
      - go mod tidy
      - dlv debug --headless --listen=:2345 --api-version=2 --accept-multiclient
        ./examples/deepresearch/cmd -- 
          {{.CLI_ARGS}}

  ex-deepresearch:
    cmds:
      - go mod tidy
      - go run ./examples/deepresearch/cmd {{.CLI_ARGS}}

  ex-cook:
    cmds:
      - go mod tidy
      - go run ./examples/cook/cmd {{.CLI_ARGS}} | fblog -d -x time

  ex-cook-clock:
    cmds:
      - go mod tidy
      - go run ./examples/cook/cmd {{.CLI_ARGS}} | fblog -d -x time
      - ssh clock@localhost:7855

  ex-cook-delve:
    cmds:
      - go mod tidy
      - dlv debug --headless --listen=:2345 --api-version=2 --accept-multiclient
        ./examples/cook/cmd -- 
          {{.CLI_ARGS}} | fblog -d -x time

  install-deps:
    ignore_error: true
    cmds:
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - task: shared:install-deps
      - cargo install fblog

  am-dbg-update:
    dir: ../asyncmachine-go
    cmds:
      - go install ./tools/cmd/am-dbg

  repl-update:
    dir: ../asyncmachine-go
    cmds:
      - go install ./tools/cmd/arpc

  am-dbg-kill:
    cmd: killall am-dbg

  am-dbg-delve:
    silent: false
    dir: ../asyncmachine-go
    cmd: dlv debug --headless --listen=:2345 --api-version=2 --accept-multiclient
      ./tools/cmd/am-dbg -- 
        --dir {{.SECAI_DIR}}
        --graph 3
        --clean-on-connect 
        {{.CLI_ARGS}}

  am-dbg-debug:
    silent: false
    cmd: task am-dbg -- 
      --am-dbg-addr localhost:9913
      --log-level 2
      --dir {{.SECAI_DIR}}
      --graph 3
      {{.CLI_ARGS}}

  am-dbg-delve-debug:
    silent: false
    dir: ../asyncmachine-go
    cmd: dlv debug --headless --listen=:2345 --api-version=2 --accept-multiclient
      ./tools/cmd/am-dbg -- 
        --am-dbg-addr localhost:9913
        --log-level 2
        --dir {{.SECAI_DIR}}
        --graph 3
        --clean-on-connect 
        {{.CLI_ARGS}}
