version: '3'
dotenv: [ '.env', '{{.SECAI_AGENT_DIR}}/config.env' ]
includes:
  shared:
    taskfile: ./config
    flatten: true

tasks:

  secai-start:
    requires:
      vars: [ SECAI_AGENT_DIR ]
    dir: '{{.SECAI_AGENT_DIR}}'
    cmd: task build

  secai-build:
    requires:
      vars: [ SECAI_AGENT_DIR ]
    dir: '{{.SECAI_AGENT_DIR}}'
    cmd: task build

  secai-gen-sql:
    cmds:
      - go run ./scripts/gen_sql_schema
      - go tool sqlc generate

  secai-gen-sql-agent:
    requires:
      vars: [ SECAI_AGENT_DIR ]
    dir: "{{.SECAI_AGENT_DIR}}"
    cmd: task gen-sql

  deps-wasm-graph:
    dir: web/browser
    cmd: godepgraph -tags "wasm,js" -s . | dot -Tsvg -o deps-graph.svg

  deps-wasm:
    dir: web/browser
    cmd: go list -deps 
      -f '{{ "{{" }}.ImportPath{{ "}}" }} {{ "{{" }}.Imports{{ "}}" }}'
      -tags wasm,js .
        > deps.md

  release:
    cmds:
      - task --dir {{.SECAI_AGENT_DIR}} build-wasm
      - task: gen-license
      - rm -R dist/*
      - go tool goreleaser release --clean --skip publish --skip validate

  gen-license:
    ignore_error: true
    cmds:
      - go tool go-licenses check .
      - cp LICENSE LICENSE.md
      - go tool go-licenses report ./ --template config/license.tpl >> LICENSE.md