version: '3'
dotenv: [ '.env' ]
includes:
  shared:
    taskfile: ./config
    flatten: true
    excludes: [install-deps]

tasks:

  docker:
    env:
      DOCKER_BUILDKIT: 1
    cmd: docker build -t secai/{{.SECAI_ID}}
      --build-arg SECAI_ID="{{.SECAI_ID}}"
      -f deploy/agent/Dockerfile ..

  docker-compose:
    dotenv: ["deploy/agent/agent.env"]
#    cmd: env
    cmd: docker-compose -f ./deploy/agent/docker-compose.yml
      up -d
#      up -d --force-recreate

  docker-compose-stop:
    cmd: docker-compose -f ./deploy/agent/docker-compose.yml
      down

  dev-docker:
    env:
      DOCKER_BUILDKIT: 1
    cmd: docker build -t secai/{{.SECAI_ID}}-dev
      --build-arg SECAI_ID="{{.SECAI_ID}}"
      -f deploy/agent/Dockerfile ..

  dev-docker-compose:
    dotenv: ["deploy/agent/agent.env"]
    env:
      SECAI_ENV: "-dev"
#    cmd: env
    cmd: docker-compose -f ./deploy/agent/docker-compose.yml
      up -d
#      up -d --force-recreate

  dev-docker-compose-stop:
    env:
      SECAI_ENV: "-dev"
    cmd: docker-compose -f ./deploy/agent/docker-compose.yml
      down

  install-deps:
    ignore_error: true
    cmds:
      - task: shared:install-deps
      - cargo install fblog

  am-dbg-update:
    dir: ../asyncmachine-go
    cmds:
      - go install ./tools/cmd/am-dbg

  repl-update:
    dir: ../asyncmachine-go
    cmds:
      - go install ./tools/cmd/arpc

  am-dbg-dev:
    requires:
      vars: [AM_DBG_ADDR]
    env:
      AM_DBG_ADDR: '{{.AM_DBG_ADDR}}'
    desc: Start the TUI debugger
    silent: false
    ignore_error: true
    dir: ../asyncmachine-go
    cmd: task am-dbg -- 
      --log-level 2
      --dir "{{.SECAI_DIR_ABS}}"
      --output-diagrams 3
      --output-clients
      --listen-on {{.AM_DBG_ADDR}}
      {{.CLI_ARGS}}

  dashboard-repl-dev:
    ignore_error: true
    requires:
      vars: [SECAI_DIR, SECAI_ID]
    env:
      SECAI_DIR_ABS: "{{.SECAI_DIR_ABS}}"
    dir: ../asyncmachine-go
    desc: Start a dashboard with am-dbg and a REPL
    cmds:
      - task: am-dbg-dashboard-exit
      - zellij --session secai-dash-{{.SECAI_ID}}
          --new-session-with-layout {{.USER_WORKING_DIR}}/config/dash-repl.kdl
      - task: am-dbg-dashboard-exit

  dashboard-wide-narrow-dev:
    ignore_error: true
    requires:
      vars: [SECAI_DIR, SECAI_ID]
    dir: ../asyncmachine-go
    desc: Start a dashboard with 2 instances of am-dbg
    env:
      SECAI_DIR_ABS: "{{.SECAI_DIR_ABS}}"
    cmds:
      - task: am-dbg-dashboard-exit
      - zellij --session secai-dash-{{.SECAI_ID}}
          --new-session-with-layout {{.USER_WORKING_DIR}}/config/dash-wide-narrow.kdl
      - task: am-dbg-dashboard-exit

  dashboard-wn-repl-dev:
    ignore_error: true
    requires:
      vars: [SECAI_DIR, SECAI_ID]
    env:
      SECAI_DIR_ABS: "{{.SECAI_DIR_ABS}}"
    dir: ../asyncmachine-go
    desc: Start a dashboard with 2 instances of am-dbg and a REPL
    cmds:
      - task: am-dbg-dashboard-exit
      - zellij --session secai-dash-{{.SECAI_ID}}
          --new-session-with-layout {{.USER_WORKING_DIR}}/config/dash-wide-narrow-repl.kdl
      - task: am-dbg-dashboard-exit

  am-dbg-delve:
    silent: false
    dir: ../asyncmachine-go
    cmd: dlv debug --headless --listen=:2345 --api-version=2 --accept-multiclient
      ./tools/cmd/am-dbg -- 
        --dir {{.SECAI_DIR}}
        --graph 3
        --clean-on-connect 
        {{.CLI_ARGS}}

  am-dbg-debug:
    silent: false
    cmd: task am-dbg -- 
      --am-dbg-addr localhost:9913
      --log-level 2
      --dir {{.SECAI_DIR}}
      --graph 3
      {{.CLI_ARGS}}

  am-dbg-delve-debug:
    silent: false
    dir: ../asyncmachine-go
    cmd: dlv debug --headless --listen=:2345 --api-version=2 --accept-multiclient
      ./tools/cmd/am-dbg -- 
        --am-dbg-addr localhost:9913
        --log-level 2
        --dir {{.SECAI_DIR}}
        --graph 3
        --clean-on-connect 
        {{.CLI_ARGS}}
