// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
)

const addCharacter = `-- name: AddCharacter :one
INSERT INTO characters (result)
VALUES (?)
RETURNING id
`

func (q *Queries) AddCharacter(ctx context.Context, result string) (int64, error) {
	row := q.db.QueryRowContext(ctx, addCharacter, result)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const addResource = `-- name: AddResource :one
INSERT INTO resources (key, value)
VALUES (?, ?)
RETURNING id
`

type AddResourceParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) AddResource(ctx context.Context, arg AddResourceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, addResource, arg.Key, arg.Value)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteAllCharacter = `-- name: DeleteAllCharacter :exec
DELETE
FROM characters
`

func (q *Queries) DeleteAllCharacter(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllCharacter)
	return err
}

const deleteAllResources = `-- name: DeleteAllResources :exec
DELETE
FROM resources
`

func (q *Queries) DeleteAllResources(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllResources)
	return err
}

const getCharacter = `-- name: GetCharacter :one
SELECT id, result
FROM characters
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetCharacter(ctx context.Context) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacter)
	var i Character
	err := row.Scan(&i.ID, &i.Result)
	return i, err
}

const getResources = `-- name: GetResources :many
SELECT id, "key", value
FROM resources
`

func (q *Queries) GetResources(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, getResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(&i.ID, &i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
