version: '3'
dotenv: [ '.env' ]
includes:
  shared:
    taskfile: ./config/Taskfile.yml
    flatten: true
    optional: true

env:
  SECAI_ID: "research"

tasks:

  sync:
    cmds:
      - rm ./template.env
      - wget -O ./template.env
          https://raw.githubusercontent.com/pancsta/secai/refs/heads/main/template.env
      - rm ./config/Taskfile.yml
      - wget -O ./config/Taskfile.yml
          https://raw.githubusercontent.com/pancsta/secai/refs/heads/main/config/Taskfile

  # TODO custom tasks go here
