version: '3'
dotenv: [ '.env' ]
includes:
  shared:
    taskfile: ./config/Taskfile.yml
    flatten: true
    optional: true

env:
  SECAI_ID: "research"

tasks:

  sync-taskfile:
    ignore_error: true
    cmds:
      - go mod tidy
      - rm ./config/Taskfile.yml
      - wget -O ./config/Taskfile.yml
          https://raw.githubusercontent.com/pancsta/secai/refs/heads/main/config/Taskfile.yml

  # TODO agent's tasks go here
