version: 3

tasks:

  start:
    requires:
      vars: [ SECAI_ID ]
    deps: [build]
    desc: Start the agent
    cmd: ./{{.SECAI_ID}} {{.CLI_ARGS}}

  logs:
    requires:
      vars: [ SECAI_ID ]
    deps: [build]
    cmd: ./{{.SECAI_ID}} log

  # BUILD

  install-deps:
    - task: install-deps-wasm
    - go mod tidy

  install-deps-wasm:
    silent: true
    cmds:
      - mkdir -p web/assets/deps
      - wget -O web/assets/deps/chart.js --no-verbose
          https://cdn.jsdelivr.net/npm/chart.js/dist/chart.umd.js
      - wget -O web/assets/deps/daisyui@5.css --no-verbose
          https://cdn.jsdelivr.net/npm/daisyui@5
      - wget -O web/assets/deps/themes.css --no-verbose
          https://cdn.jsdelivr.net/npm/daisyui@5/themes.css
      - wget -O web/assets/deps/tailwind@4.js --no-verbose
          https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4
      - wget -O web/assets/deps/utils.js --no-verbose
          https://raw.githubusercontent.com/imhvost/chart-utils/refs/heads/master/dist/chart-utils.min.js

  gen-sql:
    cmds:
      - go run ./scripts/gen_sql_schema
      - go tool sqlc generate

  build:
    requires:
      vars: [ SECAI_ID ]
    deps: [build-wasm]
    cmd: go build -o {{.SECAI_ID}} ./cmd

  build-prod:
    requires:
      vars: [ SECAI_ID ]
    deps: [build-wasm-prod]
    cmd: go build -ldflags="-w -s" -o {{.SECAI_ID}} ./cmd

  # WASM

  build-wasm:
    env:
      GOOS: js
      GOARCH: wasm
    deps: [install-deps-wasm]
    cmds:
      - mkdir -p web
      - go build -o web/app.wasm
          github.com/pancsta/secai/web/browser/cmd

  build-wasm-prod:
    env:
      GOOS: js
      GOARCH: wasm
    deps: [install-deps-wasm]
    cmds:
      - mkdir -p web
      - go build -ldflags="-s -w" -o web/app.wasm
          github.com/pancsta/secai/web/browser/cmd
      # TODO breaks
#      - wasm-opt -O3 web/app.wasm -o web/app.wasm --enable-bulk-memory-opt

  # TUI

  tui:
    requires:
      vars: [ SECAI_TUI_PORT_SSH ]
    ignore_error: true
    desc: Connect to TUI via SSH
    cmd: ssh desktop@localhost -p {{.SECAI_TUI_PORT_SSH}}
      -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

  tui-auto:
    ignore_error: true
    desc: Connect to TUI via SSH and keep reconnecting
    cmd: |
      while true; do
        task tui
        sleep 3
      done

  # CONFIG

  env:
    desc: Generate .env from config.kdl
    cmd: go run ./cmd env

  sync-configs:

    desc: Pull the newest `./template.env`, `./config`, and `./docker`
    ignore_error: true
    cmd: |
      files=(
        "./template.env"
        "./config/Taskfile.yml" 
        "./deploy/agent-metrics/docker-compose.yml"
        "./deploy/agent-metrics/loki.yaml"
        "./deploy/agent-metrics/otel-collector-config.yaml"
        "./deploy/agent-metrics/prometheus.yml"
      )
      mkdir -p deploy/agent-metrics
      for file in "${files[@]}"; do
        rm -f "$file"
        wget -O "$file" "https://raw.githubusercontent.com/pancsta/secai/refs/heads/main${file:1}"
      done

  # DEBUG

  am-dbg:
    desc: Start the TUI debugger
    silent: false
    ignore_error: true
    cmd: go tool am-dbg 
      --dir "{{.SECAI_DIR}}"
      --output-diagrams 1
      --output-clients
      --clean-on-connect
      {{.CLI_ARGS}}

  repl:
    desc: Start the REPL
    cmd: go tool arpc -d "{{.SECAI_DIR}}"

  metrics-prometheus:
    desc: Open Prometheus
    deps:
      - start-docker-metrics
    cmd: xdg-open http://localhost:9091/

  metrics-grafana:
    desc: Open Grafana
    deps:
      - start-docker-metrics
    cmd: xdg-open http://localhost:3000/dashboards

  metrics-jaeger:
    desc: Open Jaeger
    deps:
      - start-docker-metrics
    cmd: xdg-open http://localhost:16686/search

  metrics-start:
    desc: Start docker-compose with Grafana and Jaeger for agents
    cmds:
      - docker-compose -f deploy/agent-metrics/docker-compose.yml up -d --force-recreate
      - |
        echo Grafana: http://localhost:3000
        echo Jaeger: http://localhost:16686