// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type Character struct {
	ID     int64  `json:"id"`
	Result string `json:"result"`
}

type Ingredient struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	Amount string `json:"amount"`
}

type Joke struct {
	ID   int64  `json:"id"`
	Text string `json:"text"`
}

type Resource struct {
	ID    int64  `json:"id"`
	Key   string `json:"key"`
	Value string `json:"value"`
}
