// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type Prompt struct {
	ID          int64          `json:"id"`
	SessionID   string         `json:"session_id"`
	Agent       string         `json:"agent"`
	State       string         `json:"state"`
	System      string         `json:"system"`
	HistoryLen  int64          `json:"history_len"`
	Request     string         `json:"request"`
	Response    sql.NullString `json:"response"`
	CreatedAt   time.Time      `json:"created_at"`
	MachTimeSum int64          `json:"mach_time_sum"`
	MachTime    string         `json:"mach_time"`
}
